### ISSUE TITLE
Package cannot be installed anymore after latest update

### ISSUE THREAD

**Issue by kondofersky** [exasol/r-exasol#110]
After the latest Update, the package cannot be installed via `install_github("EXASOL/r-exasol")` anymore:
```
> install_github("EXASOL/r-exasol")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`EXASOL`) and repo name (`r-exasol`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.
```

Fast workaround would be to ignore latest changes: `install_github("EXASOL/r-exasol@7.0.2")`.

I guess, the DESCRIPTION file is somehow messed up, but don't know exactly where the problem is.

**Comment by tomuben** [comment]
@kondofersky 
please inform which platform, R version, and most important, which version of devtools you are using.

I just tested the latest version on an Ubuntu 18.04 with R 4.1 and devtools 2.4.3.

I suspect the problem you are describing is caused by an older version of devtools. Background is that we renamed the default branch of r-exasol, some time ago, it's not master, but **main** now. It seems your version of devtools does not verify the default branch of the repository, and tries to pull master.

As a workaround you can install the latest version with:
```
devtools::install_github("EXASOL/r-exasol", ref = "main")
```

**Comment by kondofersky** [comment]
Hi @tomuben and thanks for the fast reply. Your workaraound did work for me. 

I am working on Ubuntu 20.04 with R 4.0.0 and devtools version is 2.3.0. Did not test if it installs automatically (without main = "ref") with an updated devtools package but it would be strange if this is not the case.

Thanks again!
