### ISSUE TITLE
R version dependence

### ISSUE THREAD

**Issue by sunsiyu** [EXASOL/r-exasol#25]
Hi, is it necessary to have R dependence of >= 3.3.0? thanks!

**Comment by marcelboldt** [comment]
Let's say it makes sense:

The reason is a change in garbage collection introduced in R 3.3.0: "Reference class finalizers run at exit, as well as on garbage collection." see https://stat.ethz.ch/pipermail/r-announce/2016/000602.html

the object created by dbSendQuery() is a reference class pointing to a table in Exasol. If it's finalise method is not run at termination the temporarily created table in the DB is not cleaned up.

If you can live with that you may use R < 3.3.0 if you have to. Testing was however done with R 3.3.0
